/* eslint-disable @typescript-eslint/no-explicit-any */

// NOTE:: Please add your keys in "dev/locales/i18n/en.json" files. This file will be deleted soon.
export const statusMessages: any = {
  success: {
    'EVT-001': 'Event created successfully',

    
    'EVT-002': '',
    'FL-001': '',
    'SN-001': '',
    'SN-002': 'Registrations Not Started Yet!!!',
    'SN-003': 'Registrations Closed!!!!',
    'SN-004': 'Agenda added to calendar successfully',
    'SN-005': 'Agenda removed from calendar successfully',
    'SN-006': 'Session join meeting url successfully created',
    'SN-007': 'Registration limit exceeded',
    'SN-008': `You're successfully registered for the session`,
    'SN-009': `Due to a large number of registrations, your registration has been wait listed. You will be notified shortly via mail about the status of your registration by the organizer.`,
    'SN-0010': 'Agenda unregistered successfully',
    'SN-0011': 'Agenda analytics successfully added',
    'SN-0012': 'Session added to calender successfully!!',
    'SAT-001': 'Session attndee list successfully loaded.',
    'SN-0013': '',
    'SU-001': 'upcoming sessions are successfully executed',
    'SB-001': 'Sponsor ads are successfully executed',
    'SBA-001': 'sponsor banner analytics added successfully.',
    'USR-001': 'Check email successfully',
    'USR-002': 'Sign up successfully',
    'USR-003': 'Logged in successfully',
    'CMN-001': '',
    'CMN-002': 'updated Successfully.',
    'FDL-001': 'Liked',
    'FDL-002': 'Unliked',
    'FDL-003': 'Already Liked',
    'FDC-001': 'Comment added successfully.',
    'PLT-001': '',
    'NT-001': '',
    'NT-002': '',
    'PV-001': 'Vote added successfully',
    'PV-002': 'Vote removed successfully',
    'PA-001': 'poll updated successfully',
    'EPO-001': 'Event poll option added successfully',
    'EFC-001': '',
    'EFD-001': 'Event feed deactivated successfully',
    'EFD-002': 'Event feed comment removed successfully',
    'NT-005': 'Note updated successfully.',
    'NT-006': 'Note deleted successfully.',
    'PF-001': 'Poll created successfully',
    'FD-001': 'Feed deleted successfully',
    'FD-002': 'Feed activated successfully',
    'FD-003': 'Feed created successfully',
    'USR-004': 'Profile updated',
    'USR-005': '',
    // 'USR-006': 'Logout successfully',
    'USR-006': '',
    'USR-007':
      'Your login code has been sent to your registered email address. Please check your Spam folder if you have not received it',
    'FCD-001': 'Comment deleted successfully',
    'BM-001': 'Bookmark successfully added.',
    'BM-003': 'Bookmark successfully removed.',
    'BM-005': 'Bookmark get successfully',
    'PP-001': 'Feed post pin successfully',
    'PP-002': 'Feed post unpin successfully',
    'EXB-001': '',
    'RP-001': 'Report is already exist for this post',
    'RP-002': 'Report post successfully',
    'PR-001': '',
    'GCH-001': 'Message deleted successfully.',
    'GCH-002': 'Message added successfully.',
    'GCH-003': 'Reaction added successfully!',
    'EXB-002': 'Business card details shared.',
    'URL-001': 'fetched siged url successfully.',
    'QA-001': 'Upgrade your ticket to post comments in this community',
    'QA-002': 'Comment posted, Please wait for the organiser to approve',
    'QA-003': 'Question posted. Please wait for the organiser to approve.',
    'OL-001': 'Organisation list fetch successfully',
    'FDI-005': '',
    'FDI-001': 'Interest submitted successfully',
    'FDI-002': 'Already interested!',
    'FDI-003': 'Already removed!',
    'FDI-004': 'Interest removed successfully',
    'BRIF-001': '',
    'BRIF-002': 'Briefcase action successfully registered',
    'BRIF-003': '',
    'BRIF-004': 'Briefcase notes successfully download',
    'BRIF-005': 'The file has been added to your briefcase',
    'BRIF-006': 'File has been successfully removed from the briefcase',
    'BRIF-007': 'File has been hidden',
    'BRIF-008': 'File has been unhidden',
    'EXB-003': 'Exhibitor analytics data successfully downloaded',
    'AGC-001': 'Reaction added!',
    'AGC-002': 'Pinned successfully!',
    'AGC-003': 'Unpinned successfully!',
    'AGC-004': 'Reaction removed!',
    'MEET-001': 'Meeting created successfully.',
    'MEET-002': 'Meeting cancelled Successfully.',
    'MEET-015': 'Meeting declined.',
    'MEET-016': 'Meeting accepted.',
    'QA-004': 'Agenda not found',
    'QA-005': `Comment doesn't exist`,
    'QA-006': `Comment already deleted`,
    'QA-007': 'Question removed successfully',
    'QA-008': 'Comment Deleted',
    'QA-009': 'Approved successfully.',
    'QA-010': 'Rejected successfully.',
    'QA-011': 'Upvoted Successfully',
    'QA-012': 'Upvote Removed',
    'QA-013': 'Action not found',
    'QA-014': 'Only speaker or host can perfrom the action',
    'QA-015': `You don't have permission to do this`,
    'QA-016': 'Only speaker or host can perfrom the action',
    'QA-017': 'Agenda Not found',
    'QA-018': `Question doesn't exits`,
    'QA-019': `You already upvoted this question`,
    'QA-020': `You already removed upvoted to this question .`,
    'QFU-001': 'question votes are successfully executed.',
    'MT-001': 'Meeting created successfully.',
    'RAT-001': 'Rated successfully',
    'MT-002': 'Meeting updated successfully.',
    'LPL-001': 'Poll live list fetched successfully',
    'PAV-001': '',
    'PC-001': 'Live poll successfully created',
    'JR-001': 'Room join successfully.',
    'JR-008': 'Room join validated successfully.',
    'RLU-001': 'Live room user list successfully',
    'RMLC-001': 'Room LiveChat listed successfully.',
    'RMLC-003': 'Room LiveChat deleted successfully.',
    'CTS-001': 'Contests list fetched successfully',
    'CTS-002':
      'Your response has been successfully recorded. The results will be out soon.',
    // 'CTS-003': 'Comment was created successfully',
    'CTS-003': '',
    'CTS-004': 'Already Liked',
    'CTS-005': 'Comment liked successfully',
    'CTS-018': 'Comment disliked successfully',
    'CTS-006': 'Comment Deleted',
    'CTS-007': 'Comment Likes list fetched successfully',
    'CTS-008': 'Contest quiz list fetched successfully',
    'CTS-009': 'Contest quiz winner list fetched successfully',
    'CTS-010': 'Contest response list fetched successfully',
    'CTS-011': 'Winner is not declared for this contest.',
    'CTS-012': '',
    // 'CTS-012': 'Feed liked successfully',
    // 'CTS-019': 'Feed disliked successfully',
    'CTS-019': '',
    'CTS-013': 'Feed Delete successfully',
    'CTS-014': 'Winner list fetched successfully',
    'USM-001': 'User slot meeting list loaded successfully',
    'EXP-001': 'Exhibitor info updated successfully',
    'EXP-002': 'Exhibitor analytics fetched successfully',
    'EXP-003': 'Attendee lead status updated successfully',
    'EXP-004': 'Attendee engagement list fetched successfully',
    'LN-001': 'Join lounge successfully',
    'LN-002': 'Left lounge successfully',
    'LN-003': 'Updated channel token successfully',
    'ST-001': '',
    'ST-002': 'Invalid Notification Type',
    'ST-003': 'Notification Settings Updated',
    'ST-004': 'Saved successfully.',
    'ST-005': 'Password changes successfully, please Sign in again',
    'ST-006': 'The current password you entered is incorrect',
    'ST-007': 'Updated',
    'RL-001': 'Leave from room successfully.',
    'SAVR-001': 'Send audio video request successfully',
    'AAVR-001': 'Accept audio video request successfully',
    'SUR-001': 'Answer saved!',
    'TKT-001': 'Ticket downloaded successfully',
    'UCB-001': 'User successfully make busy schedule on calender',
    'UCR-001': 'User removed busy schedule from calender',
    'SRHR-001': 'Send raise hand request successfully',
    'ARHR-001': 'Accept raise hand request successfully',
    'OAVBM-001': 'Off audio video by moderator successfully',
    'MAA-001': 'mute Audio Approved successfully',
    'CU-001': 'User updated successfully.',
    'CQA-001': 'Question accepted!',
    'CQA-002': 'Question rejected!',
    'CQA-003': 'Upvoted successfully!',
    'CQA-004': 'Upvoted removed!',
    'CQA-005': 'Answer added successfully!',
    'CQA-006': 'Question posted successfully!',
    'CQA-007': 'Deleted successfully!',
    'KO-001': 'Kick off successfully.',
    'BU-001': 'ban user successfully.',
    'BU-002': 'unban user successfully.',
    'LPD-001': 'Link preview data listing',
    'AC-001': 'Channel Access Token listed successfully.',
    'CPO-001': 'Voted successfully!',
    'CPO-002': 'Poll is live!',
    'CPO-003': 'Poll is created!',
    'CPO-004': 'Poll edited successfully!',
    'CPO-005': 'Poll ended!',
    'CPO-006': 'Poll results are visible!',
    'CPO-007': 'Poll results are hidden!',
    'CPO-008': 'Poll deleted!',
    'CPO-009': 'Poll duplicated!',
    'USR-008': 'Password updated successfully',
    'SSJ-001': 'screen share join request successfully',
    'SSL-001': 'screen share leave successfully',
    'OAV-001': 'Off audio video successfully',
    'ER-001': 'End room successfully',
    'USR-009': 'Token validate successfully',
    'USR-010': 'Otp validate successfully!',
    'CHT-002': 'Chat Not found',
    'CHT-003': 'Cleared',
    'TZ-001': 'Timezone list fetched successfully',
    'LM-001': 'Language list fetched successfully',
    'CHT-004':
      "You can't send message to this user. \n This user has blocked you",
    'CHT-005': 'You have blocked this user',
    'CHT-006': 'User has disabled the chat feature.',
    'UNSUB-001': 'Successfully unsubscribed',
    'CHT-007': 'Message not found.',
    'CHT-008': 'Reaction updated',
    'MEET-018': 'Meeting joined successfully.',
    'MEET-019': 'Meeting leave successfully',
    'CHT-009': 'Not found!!',
    'CTS-015': 'Report added successfully',
    'CHT-010': 'Maked as read',
    'CTS-016': 'Please Wait for the organiser to approve your entry',
    'CTS-017': 'Entry created successfully',
    'UTIL-001': 'Push to kafka successfully',
    'RM-002': 'Room list fetched successfully',
    'RI-001': 'Room Info fetched successfully',
    'SPH-001': 'Speaker and Host userIds successfully loaded.',
    'SLS-001': 'Session live history successfully updated.',

    /**
     * Survey
     */
    SURVEY_NOT_FOUND: 'Survey not found.',
    SURVEY_RESPONSE_NOT_FOUND: 'Response not found.',
    SURVEY_NOT_STARTED_YET: 'The survey will begin shortly.',
    SURVEY_ENDED: 'Sorry, this survey has ended.',
    SURVEY_QUOTA_EXCEEDS:
      'We have already received the required number of responses for this survey. Sorry!',
    SURVEY_STARTED: 'The survey has started.',
    SURVEY_RESPONSE_NOT_EXISTS: "This response doesn't exist.",
    SURVEY_QUESTION_NOT_EXISTS: "This survey question doesn't exist.",
    SURVEY_ADDED: 'Survey added.',
    SURVEY_UPDATED: 'The survey details have been updated.',
    SURVEY_ALREADY_DEACTIVATED: 'This survey is already deactivated.',
    SURVEY_ALREADY_DELETED: 'This survey has been deleted.',
    SURVEY_DELETED: 'Survey deleted.',
    QUESTION_ALREADY_DELETED: 'This question has been deleted.',
    QUESTION_DELETED: 'Question deleted.',
    QUESTION_ADDED: 'A new question has been added.',
    ALREADY_ANSWERED: 'You have already answered this survey once.',
    SURVEY_COMPLETED: 'Survey has already been completed.',

    /**
     * Engage
     */
    CONTEST_RESPONSE_RECORDED:
      'Response successfully recorded. Contest results will be out soon.',
    CONTEST_NOT_FOUND: 'Contest not found.',
    CONTEST_NOT_ACTIVE: 'Contest not active.',
    CONTEST_ENDED:
      'Contest ended. Check the ongoing section for active contests.',
    CONTEST_ALREADY_SUBMIT: 'Contest entry already submitted.',
    CONTEST_UPLOAD_IMAGE: 'Upload Image',
    CONTEST_UPLOAD_VIDEO: 'Upload Video',
    WAIT_MODERATOR_APPROVE: "Kindly wait for the organiser's approval.",
    COMMENT_NOT_ALLOW: 'Comment on entry not allowed.',

    /**
     * Booths
     */
    EXHIBITOR_NOT_FOUND: 'Exhibitor not found.',
    SPONSOR_NOT_FOUND: 'Sponsor not found.',
    INVALID_FILE: 'Invalid File',
    IMAGE_UPLOAD: 'Please upload image',
    RATING_SAVED: 'Rating Saved',
    INVALID_FORMAT: 'Upload valid file format',
    LARGE_IMAGE_SIZE:
      'Re-upload images within the allowed dimensions. Images greater than 1024 x 1024 pixels are not allowed.',
    SPOTLIGHT_IMAGE_SIZE_ERR:
      'Upload another image as minimum width and height should be 1036x320px.',
    LIST_BANNER_IMAGE_SIZE_ERROR:
      'Upload another image as minimum width and height should be 840x220px.',
    INVALID_FORMAT_FOR_SURVEY:
      'Upload valid format of the file (image, pdf, doc, ppt and excel).',

    /**
     * People
     */
    ATTENDEE_NOT_FOUND: 'Attendee not found.',
    SPEAKER_NOT_FOUND: 'Speaker not found.',
    BUSINESS_CARD_TARGET_NOT_IN_COMMUNITY:
      "You can't request a user who is not a part of this Community.",
    BUSINESS_CARD_REQUEST: 'Business card request sent!',
    BUSINESS_CARD_ALREADY_REQUESTED: 'You have already requested.',
    BUSINESS_CARD_ERROR: "You can't perform this operation.",
    USER_HAS_BLOCKED_YOU:
      "You can't send a message to a user who has blocked you.",
    CANT_BLOCK_USER_CHAT:
      "You can't block a user who is not in this Community.",
    CHAT_USER_BLOCKED_SUCCESS: 'User blocked successfully.',
    CHAT_USER_UNBLOCKED_SUCCESS: 'User unblocked successfully.',
    COMMUNITY_NOT_ACTIVE: 'User not active in the Community.',
    USER_NOT_FOUND: 'User not found.',

    /**
     * Login/Signup
     */
    INVALID_ACCESS_TOKEN: 'Please login again.',
    FB_REGISTER_FAIL: 'Facebook login issue. Try again.',
    EVENT_NOT_FOUND: 'Event not found.',
    EVENT_NOT_ACTIVE: 'Event not active.',
    INVALID_CREDENTIAL: 'Enter valid credentials.',
    EMAIL_MISSING: 'E-mail ID missing.',
    INVALID_EMAIL: 'Enter a valid e-mail.',
    ACCOUNT_INACTIVE: 'Account inactive.',
    ACCOUNT_BLOCKED: 'Entry not permitted by the organiser.',
    ACCOUNT_DELETED: 'Account deleted.',
    EMAIL_NOT_REGISTERED: 'Unregistered e-mail ID. Enter registered e-mail ID.',
    LOGIN_SETTINGS_CHANGED: 'Login settings changed. Restart the app again.',
    LOGIN_ID_NOT_EXIST: "Login ID doesn't exist.",
    LOGIN_ID_NOT_EXIST_CONTACT_SUPPORT:
      "Login ID doesn't exist. Contact %%SUPPORT_EMAIL%% for more information.",
    INVALID_OTP: 'Enter a valid Login Code to continue.',
    CONFIRM_PASSWORD_MISMATCH: 'Confirm password mismatch.',
    INVALID_PHONE_NUMBER: 'Enter a valid phone number.',
    RSVP_ID_MISSING: 'RSVP ID missing.',
    WAITLIST_ID_MISSING: 'Waitlist ID missing.',
    TRANSACTION_INDIVIDUAL_ID_MISSING: 'Transaction individual ID missing.',
    INVALID_LOGIN_TYPE: 'Invalid Login type.',
    USER_NOT_IN_EVENT: 'User not present in any event.',
    USER_IN_MULTIPLE_EVENT:
      'User in multiple events. Please contact organizer.',
    INVALID_TOKEN: 'Invalid token',
    // LOGIN_SUCCESS: 'Logged in successfully',
    LOGIN_SUCCESS: '',
    OTP_VERIFIED: 'Login Code verified',
    EMAIL_ALREADY_REGISTERED:
      'Email ID already registered. Use current ID or login in with another ID.',
    LOGIN_FAIL_USER_NOT_IN_EVENT:
      'Login failed. Unregistered user for this event.',
    CONTACT_ADMIN_FOR_LOGIN_DETAILS:
      'Contact event admin to provide login credentials.',
    CONTACT_ADMIN_FOR_LOGIN_DETAILS_CONTACT_SUPPORT:
      'Contact event admin at %%SUPPORT_EMAIL%% to provide login credentials.',
    OTP_SENT_TO_PHONE_NUMBER: 'Login Code sent to your phone number.',
    ACCOUNT_ACCESS_LOCK: 'Account locked. Please try after %%min%% min.',
    MEETING_REQUEST_LIMIT_OVER:
      'Sorry, you reached the maximum number of requests.',
    MEETING_CONFIRM_LIMIT_OVER_FOR_USER:
      'Sorry, you have reached the maximum number of meetings.',
    MEETING_CONFIRM_LIMIT_OVER_FOR_ANOTHER_USER:
      'Sorry, the user has reached the maximum number of meetings.',
    PASWORD_LENGTH_ERROR: 'Minimum 8 characters password required.',
    OTP_BEFORE_TIME: 'You can try for a new Login Code after 30 seconds.',
    ACCOUNT_BLOCKED_FOR_SOMETIME:
      'Too many unsuccessful attempts. Try again later.',
    INCORRECT_CREDENTIALS: 'Invalid credentials',
    OTP_EXPIRED: 'Login Code expired. Generate a new one.',
    OTP_ACCOUNT_BLOCKED_FOR_SOMETIME:
      'Multiple Login Code requests. Try again later.',
    PASSWORD_STRENGTH:
      'Password must be minimum 8 characters with digits, lowercase, uppercase and special characters.',
    INCORRECT_PASSWORD_SUPPORT:
      'Enter correct password or contact %%SUPPORT_EMAIL%% for support.',

    /**
     * Home
     */
    POLL_OPTIONS: 'Please provide options.',
    DELETED_FEED: 'This Feed has been deleted.',
    FEED_NOT_ACTIVE: 'Post not Active',
    FEED_ALREADY_LIKED: 'Already Liked',
    // FEED_LIKE: 'Liked',
    // FEED_UNLIKE: 'Unliked',
    FEED_UNLIKE: '',
    FEED_LIKE: '',
    FEED_NOT_EXIST: "Post doesn't exist.",
    FEED_REPORTED:
      'Thanks for reporting the post. Necessary action will be taken.',
    FEED_NOT_APPROVED: 'Post not approved.',
    FEED_UPGRADE_TICKET:
      'Upgrade your ticket to post comments in this Community.',
    FEED_COMMENT_MSG: "Comment posted, please wait for organiser's approval.",
    FEED_COMMENT_NOT_FOUND: "Comment doesn't exist.",
    FEED_COMMENT_ALREADY_DELETED: 'Comment already deleted.',
    FEED_COMMENT_DELETE: 'Comment Deleted',
    FEED_COMMENT_REPORTED:
      'Thanks for reporting the comment. Necessary action will be taken.',
    FEED_NOT_FOUND: 'Feed not found.',
    POLL_CREATED: 'Poll Created',
    POST_PINDDED: 'Post Pinned',
    POST_UNPINNDED: 'Post Unpinned',

    /**
     * Chat & Notifications
     */
    NOTIFICATION_LIST_CLEAR: 'Cleared',
    CANT_MSG_USER: "You can't message this user.",
    CHAT_DISABLED: 'User disabled chat feature.',
    CHAT_PERMISSION_ERROR: "You can't message this user.",
    CHAT_NOT_FOUND: 'Chat not found.',
    PROVIDER_NOT_FOUND: 'Media Provider not found.',
    MEDIAID_NOT_FOUND: 'MediaId not found.',
    NO_CHAT_WITH_TARGET: 'No chat with target.',
    CANT_DELETE_CHAT: 'You can only delete your chats.',
    DELETE_SINGLE_CHAT_SUCCESS: 'Chat deleted successfully.',
    DELETE_MULTI_CHAT_SUCCESS: 'Chats deleted successfully.',
    NOTIFICATION_MEETING_SENT: 'has sent you a meeting request.',
    NOTIFICATION_MEETING_ACCEPT: 'has accepted your meeting request.',
    NOTIFICATION_MEETING_ACCEPT_WITH_VENUE:
      'has accepted your meeting request. The venue for the meeting is:',
    NOTIFICATION_MEETING_VENUE: 'The venue for the meeting is:',
    NOTIFICATION_MEETING_REJECT: 'has declined your meeting request.',
    NOTIFICATION_FEED_TAG: 'mentioned you in a post.',
    NOTIFICATION_FEED_LIKE: 'liked your post.',
    NOTIFICATION_FEED_INTEREST: 'has shown interest in your post.',
    NOTIFICATION_FEED_COMMENT: 'commented on your post.',
    NOTIFICATION_BUSINESS_CARD_SENT: 'has sent you a Business Card request.',
    NOTIFICATION_BUSINESS_CARD_ACCEPT:
      'has accepted your Business Card request.',
    NOTIFICATION_BUSINESS_CARD_REJECT:
      'has rejected your Business Card request.',
    NOTIFICATION_PROFILE_VIEW: 'viewed your profile',

    /**
     * Rooms
     */
    ROOM_IS_NOT_LIVE: 'Room not live yet. Try again later.',
    ROOM_NOT_FOUND: 'Room not found.',
    ROOM_FULL: 'Room is full. Try again in sometime.',
    CAN_NOT_JOIN_ROOM: 'You cannot join the room.',
    INCORRECT_ROOM_CODE: 'Enter a valid code to enter the Room.',
    ROOM_NOT_STARTED_YET: 'Room not started yet.',
    AGENDA_COMMENT_NOT_EXISTS: "Question doesn't exist.",
    INVALID_TIMEZONE: 'Invalid Timezone',
    LOUNGE_LEFT_MEETING: 'You have left the meeting.',
    LOUNGE_MEETING_TIME_END: 'The Meeting has ended.',
    FEEDBACK: 'Thanks for your feedback.',
    ROOM_USER_BAN: 'You are banned in this Room.',
    ROOM_AV_ALREADY_SHARED: 'Audio/Video already shared.',
    ROOM_AV_ALREADY_REQUESTED: 'Audio/Video already requested.',
    REQUESTED_SUCEESSFULLY: 'Request Sent Successfully.',
    USER_ALREADY_SHARED_AV: 'User Audio/Video already shared.',
    USER_NOT_REQUESTED_SHARED_AV: 'User has not requested for Audio/Video.',
    ALREADY_RAISE_HAND_IN_CALL:
      'Remove an attendee in the call who has already raised hand and then add this attendee.',
    RECORDING_REQUEST_ALREADY: 'Recording request already recieved,',
    RECORDING_NOT_ALLOW: 'Recording is not allowed in this Room.',
    CAN_NOT_END_ROOM: 'You cannot end the Room.',
    USER_NOT_EXITS_CHANNEL: "User doesn't exits in this channel",
    CHANNEL_NOT_EXITS: "channel doesn't exists",
    PERMISSION_ERROR: "You don't have permission to do this",

    /**
     * Longe
     */
    ACTIVATE_LOUNGE_TABLE_FIRST: 'Turn on Lounge table first.',
    TABLE_ADDED: 'Lounge table added.',
    LOUNGE_TABLE_NOT_EXISTS: 'Lounge table does not exit.',
    LOUNGE_TABLE_DELETED: 'Lounge table sucessfully deleted',
    ACTIVATE_LOUNGE_FIRST: 'Turn on Lounge networking first.',
    LOUNGE_SETTING_UPDATED: 'Lounge setting updated',
    LOUNGE_NOT_AVAILABLE: 'Lounge is not available in this event.',
    TABLE_LIST_LIMIT_DONE:
      'Table limit exceeded. Contact Administrator to add more tables.',
    ADMIN_ACTIVATE_LOUNGE_FIRST:
      'Contact Administrator to activate the Networking Lounge.',
    LOUNGE_IS_OFF: 'Lounge networking is off currently.',
    SLOT_IS_CLOSED: 'Sorry, this slot is closed for video call.',
    SEAT_NUMBER_NOT_EXITS: 'This seat number does not exist.',
    ALREDAY_JOINED: 'Leave the current table to join a new table.',
    TABLE_BUSY: 'Sorry, this table is currently busy.',
    SOMEONE_ELSE_TOOK_SEAT: 'Sorry, this seat is taken.',
    EXHIBITOR_LOUNGE_IS_OFF: 'Currently Exhibitor Lounge networking is off.',
    EXHIBITOR_UNAVAILABLE:
      'Currently the exhibitor is unavailable for a meeting.',
    UNKNOWN_EXHIBITOR: 'Unknown exhibitor for this seat.',
    EXHIBITOR_ALREADY_JOINED: 'One of your exhibitors is already there.',
    CHANNEL_TIME_LESS_TO_UPDATE:
      'Updating meeting count 2 minutes before not allowed',
    ACTIVATE_EXHIBITOR_LOUNGE_FIRST: 'Please turn on Exhibitor Lounge first.',
    ADMIN_EXHIBITOR_ACTIVATE_LOUNGE_FIRST:
      'Contact administrator to activate the Exhibitor Networking Lounge.',
    ACTIVATE_ATTENDEE_LOUNGE_FIRST: 'Turn on Attendee Lounge first.',
    INVALID_TABLE_CAPACITY: 'Invalid table capacity.',
    SPONSOR_LOUNGE_IS_OFF: 'Sponsor Lounge networking is currently off.',
    SPONSOR_UNAVAILABLE: 'The sponsor is currently unavailable for a meeting.',
    UNKNOWN_SPONSOR: 'Unknown sponsor for this seat.',
    ACTIVATE_SPONSOR_LOUNGE_FIRST: 'Turn on Sponsor Lounge first.',
    ADMIN_SPONSOR_ACTIVATE_LOUNGE_FIRST:
      'Contactadministrator to activate the Sponsor Networking Lounge.',

    /**
     * Profile, setting, scheduele
     */
    ADD_FILE_BRIEFCASE: 'This file has been added to your Briefcase.',
    HIDE_FILE_BRIEFCASE: 'This file is hidden.',
    UNHIDDEN_FILE_BRIEFCASE: 'This file has been unhidden.',
    REMOVE_FILE_BRIEFCASE: 'This file has been removed from the Briefcase.',
    FILE_ALREADY_IN_BRIEFCASE: 'This file already exists in your Briefcase.',
    FILE_NOT_FOUND: 'File not found.',

    /**
     * Sessions
     */
    AGENDA_NOT_FOUND: 'Agenda Not Found.',
    REMINDER_ADDED: 'Reminder Added',
    REMINDER_REMOVED: 'Reminder Removed',
    REGISTRATION_NOT_STARTED: 'Registrations Not Started Yet!',
    REGISTRATION_CLOSED: 'Registrations Closed!',
    REGISTRATION_LIMIT_EXCEED: 'Registration limit exceeded.',
    ALREADY_REGISTER_IN_SESSION: 'Already Registered',
    NOT_REGISTER_IN_SESSION: "You're Un-registered",
    SESSION_REGISTRATION_DONE: 'Registration Successful!',
    SESSION_REGISTRATION_PENDING:
      'Registration waitlisted. Status update will be sent via mail.',
    SESSION_UNREGISTERD: 'Deregisterd Successfully!',
    AGENDA_COMMENT_MSG: "Question Posted. Waiting organiser's approval.",
    POLL_DEACTIVATED: 'Poll deactivated by the user.',
    BLOCK_PERMISSION_ERROR: 'Blocking this user is not permitted.',
    ALREADY_BLOCKED: 'User is already blocked.',
    ALREADY_UNBLOCKED: 'User is already unblocked.',
    BLOCKED_IN_LIVE_CHAT: 'You are blocked for this live chat.',
    AGENDA_COMMENT_DELETE: 'Question removed successfully.',
    POLL_NOT_FOUND: "Poll doesn't exist.",
    SESSION_ENDED: "Sorry! You can't chat on ended session.",
    SAVED: 'Saved Successfully',
    REJECTED: 'Rejected Successfully',
    APPROVED: 'Approved Successfully',
    AGENDA_LIVE_POLL_CREATED: 'Poll Created',
    AGENDA_POLL_LIVE: 'Poll is Live',
    AGENDA_LIVE_POLL_END: 'Poll Ended',
    AGENDA_LIVE_POLL_SHOW: 'Poll result visible to attendees.',
    AGENDA_LIVE_POLL_HIDE: 'Poll result hidden from attendees.',
    AGENDA_LIVE_POLL_DUPLICATE: 'Poll Duplicated',
    AGENDA_LIVE_POLL_DELETED: 'Poll Deleted',
    AGENDA_LIVE_POLL_EDIT: 'Poll Edited',
    UPVOTE_ADDED: 'Upvoted Successfully',
    UPVOTE_REMOVED: 'Upvote Removed',
    CHAT_PINNED: 'Chat Pinned',
    CHAT_UNPINNED: 'Chat Unpinned',
    NOT_PERMISSION_ATTENDE_SESSION: 'Not permitted to attend the session.',
    SESSION_NOT_STARTED: 'Session yet to start. Please try again later.',
    LIVE_CHAT: 'Chat',
    QUESTION_AND_ANSWERS: 'Q&A',
    LIVE_POLLS: 'Polls',
    ATTENDEE_LIST: 'Attendees',
    SESSIONS: 'Sessions',

    /**
     * Meeting
     */
    MEETING_IN_PAST: "You can't set meeting in the past",
    SELF_MEETING: "You can't set meeting with you",
    ALREADY_MEETING_REQUESTED:
      'You have already sent a meeting request at this slot',
    OCCUPIED_SLOT: 'Your slot is occupied',
    TARGET_OCCUPIED_SLOT: 'Target slot is occupied',
    ALREADY_VENUE_BOOKED: 'Venue is already booked for this slot',
    MEETING_NOT_PENDING: 'Meeting is no longer in pending state',
    CANT_ACCEPT_PAST_MEETING: "You can't accept past meeting",
    CANT_REJECT_PAST_MEETING: "You can't reject past meeting",
    MEETING_ACCEPTED: 'Meeting accepted',
    MEETING_DECLINED: 'Meeting declined',
    MEETING_DISABLED: 'User has disabled meeting requests.',
    MEETING_PERMISSION_ERROR: "You can't send meeting request to this user",
    MEETING_CLOSE_SLOT_IN_PAST: "You can't close meeting slots in the past",
    MEETING_CLOSE_SLOT_REMOVED: 'Removed',
    NOT_IN_COMMUNITY: 'User not found in community',
    MEETING_LIMIT_OVER:
      'Your meeting quota is over, Please contact administrator to increase meeting quota',
    ALREADY_CANCEL: 'Meeting already canceled',
    MEETING_NOT_APPROVE_CANCEL: "Can't cancel, Meeting isn't approved yet.",
    CANCELED: 'Successfully canceled',
    SLOT_IS_CLOSED_MEETING: 'Sorry, this slot is closed for meeting',

    /**
     * unsubscribeUsers
     */
    UNSUBSCRIBE_SUCCESS: 'Successfully unsubscribed',
    INVALID_TYPE: 'Invalid Type',
    INVALID_URL: 'Invalid Url'
  },
  error: {
    'EVT-001': 'Error occurred in events',
    'FL-001': 'Error in filters',
    'SN-001': 'This timezone is invalid',
    'SN-002':
      'Sorry, Some parameter are missing. Please enter all required values.',
    'SN-003': 'Unhandled error occurred ',
    'SN-004': 'Agenda ID invalid ',
    'SN-006': 'Error occurred while creating session join meeting url.',
    'SN-008': 'Error occured while registering for the session.',
    'SN-009': 'Error occured while adding slot for the session.',
    'SN-0010': 'Error occurred while registering for the session.',
    'SN-0011': 'Error occurred while analytics for the session.',
    'SN-0012': 'Agenda data for user not found.',
    'SN-0014': 'Error occurred while getting live agenda',
    'SU-002': 'Error occured while getting upcoming sessions',
    'SAT-002': 'Error occured while getting session attendees',
    'SB-002': 'Error occured while getting sponsor ads',
    'SBA-002': 'Error occured while adding analytic of sponsor banner',
    'USR-001':
      'Email ID already registered, Please try another email ID or log in directly with current ID',
    'USR-002': 'Signup failed',
    'USR-003': 'Check email failed',
    'USR-004': 'Event not found',
    'USR-005': 'Login settings has been changed. Please restart the app again.',
    'USR-006':
      "Your Login id doesn't exist. Kindly contact %SUPPORT_EMAIL% for more information.",
    'USR-007': "Your login id doesn't exist",
    'USR-008': 'Account Inactive',
    'USR-009': 'Your entry to the event has been restricted by the organiser.',
    'USR-010': 'Account Deleted',
    'USR-011':
      'Password incorrect. Enter correct password or contact %SUPPORT_EMAIL for support',
    'USR-012': 'Password incorrect. Enter correct password',
    'USR-013': 'Too many unsuccessful attempts. Please try after some time',
    'USR-014': 'Invalid login code. Enter valid login code to continue',
    'USR-015': 'Login Code has expired. Please generate a new one',
    'USR-016': 'SSO is connected',
    'USR-017': 'Email not registered',
    'USR-018': 'User already exist in community',
    'USR-019': 'Event not found',
    'USR-020': 'Your entry to the event has been restricted by the organiser.',
    'USR-021': 'Error in SSO',
    'USR-030': 'No Access to community',
    'USR-031': 'Profile blocked',
    'USR-028': 'Profile not active',
    'USR-029': 'Profile removed from community',
    'TIMEZONE-001': 'Time zone not supported',
    'LDB-001': 'Error occurred in leaderboard listing.',
    'EVB-001': 'Error occurred in event banner and details listing.',
    'CMN-001': 'Listing failed.',
    'COM-001': 'Community not active.',
    'FDL-001': 'Error occured during like feed.',
    'FDC-001': 'Upgrade your ticket to post comments in this community',
    'FDC-002': 'Error while adding comment to feed',
    'CMN-002': 'Update failed.',
    'PLT-001': 'Please provide platform source',
    'PLT-002': 'Please provide url',
    'PLT-003': 'Event data not found',
    'PLT-004': 'Ticketing Platform not available for this event',
    'PLT-005': 'Community Platform not available for this event',
    'PLT-006': 'Platform not available',
    'PLT-007': 'Platform not available for this event',
    'PLT-008': 'Error in webstate.',
    'NT-003': 'Error while getting note list',
    'NT-004': 'Error while getting single note',
    'PV-001': 'Vote authentication failure',
    'PV-002': 'Poll data not available',
    'PV-003': 'Poll vote failed',
    'EPO-001': 'Please select this option first',
    'EPO-002': 'Poll option failed',
    'EFC-001': 'Feed comments failed',
    'EFD-001': 'Feed data record not found!',
    'EFD-002': 'Failed to fetch feed data',
    'EFC-002': 'Comment not found.',
    'PA-001': 'Invalid action request',
    'PA-002': 'Please Provide options',
    'PA-003': 'User does not exist in database.',
    'PA-004': 'You do not have permission to create a poll',
    'PA-005': 'Agenda does not exist with given session id',
    'PA-006': 'agenda does not exist with given host id',
    'PA-007': 'Poll do not exists',
    'PA-008': 'The poll is already live',
    'PA-009': 'The poll is already ended',
    'PA-010': 'The poll is not already live',
    'PA-011': 'The poll is already showing',
    'PA-012': 'The poll is already hidden',
    'PA-013': 'Something went wrong',
    'PA-014': 'Error occured while updating poll',
    'PF-001': 'Poll creation failed',
    'PF-002': 'Please Provide options',
    'PF-003': 'Community user not found',
    'PF-004': 'Option data not found!',
    'FD-001': 'Feed delete failed',
    'FD-002': 'This Post is not available',
    'FD-003': 'Error occured while feed create.',
    'FD-004': 'Please Wait for the organisers to approve your feed!',
    'FD-005': 'Please Upload Image!',
    'FD-006': "Feed Doesn't exist",
    'FD-007': 'Invalid Youtube Url!',
    'NT-006': 'Error while adding note',
    'USR-000': 'User not found',
    'PST-001': 'Post not found!',
    'PST-002': 'This post not approved',
    'USR-022': 'You can try for a new Login Code after 30 seconds',
    'USR-023':
      'You have requested Login Code too many times. Please try after some time',
    'FCD-001': "You can't delete this feed !",
    'FCD-002': 'Sorry , You Cant delete this comment',
    'FCD-003': 'You Cant delete this comment , Its not yours',
    'USR-024': 'Invalid token',
    'USR-025': 'Email Id missing',
    'USR-026':
      'Enter registered email ID to receive Login Code or kindly contact %%SUPPORT_EMAIL%% for more information.',
    'USR-027': 'Email ID not registered. Enter registered email ID',
    'FDB-001': 'Error occured while adding feedback.',
    'BM-002': 'Error occured while adding bookmark.',
    'BM-004': 'Error occured while removeing bookmark.',
    'BM-005': 'Error occured while fetching bookmark list',
    'PP-001': 'Failed to fetch feed data',
    'PP-002': 'Error while pin post',
    'PR-001': 'Failed to fetch report option',
    'EXB-001': 'Exhibitor details fetching failed',
    'RP-001': 'Error while report post',
    'EXB-002': 'Exhibitor not found',
    'EXB-003': 'Unknown Exhibitor',
    'EXB-004': 'Meeting limit over',
    'EXB-005': 'Seat number does not exists',
    'EXB-006': 'Can not join table before exhibitor join it',
    'EXB-008': 'Max limit reached',
    'LN-001': 'Lounge Table does not exists',
    'LN-002': 'User is already in channel',
    'LN-003': 'Table is busy',
    'LN-004': 'Someone else took seat',
    'LN-005': 'Channel does not exists',
    'LN-006': 'Lounge is off',
    'LN-007': 'Admin activate lounge first',
    'LN-008': 'slot is closed',
    'LN-009':
      "Someone's screen already share.So you cannot do the screen share",
    'GCH-001': 'Message not deleted.',
    'GCH-002': 'Message not found.',
    'GCH-003': 'User is not allowed to delete the message',
    'GCH-004': 'Booth not found!',
    'GCH-005': 'Lounge not found!',
    'GCH-006': 'Invalid type for this action!',
    'URL-001': 'Error occured during get signed url.',
    'ALC-001': 'Error while like/unlike message',
    'ALC-002': 'Already liked this message.',
    'QA-001': 'Error occured while adding question',
    'QA-002': 'Error occured while listing question',
    'OL-001': 'Failed to get organisation list',
    'FDI-005': 'Error while fetch introduction interests',
    'FD-008': 'Error while fetch feed detail',
    'FDI-001': 'Error occured while submit introduction interest.',
    'FDI-002': 'Invalid/Inactive event feed!',
    'FDT-001': 'Error occured while fetching templates.',
    'BRIF-001': 'Error occured while briefcase',
    'BRIF-002':
      'Sorry, Some parameter are missing. Please enter all required values.',
    'BRIF-003': 'File is not found',
    'BRIF-004': 'Error while generating the file',
    'EXB-007': 'Error while generating the file',
    'BRIF-005': 'The file already in your briefcase',
    'AGC-001': 'Agenda not found!',
    'AGC-002': 'Live chat is blocked!',
    'AGC-003': 'User is not allowed to send the message!',
    'AGC-004': 'Not allowed to pin the chat!',
    'AGC-005': 'Chat already pinned!',
    'AGC-006': 'Chat already un-pinned!',
    'AGC-007': 'Reaction already added!',
    'AGC-008': 'No reaction found to remove!',
    'UPLOAD-001': 'Please send a valid upload type',
    'JR-001': 'Room is not live yet. Please try again later',
    'JR-002': 'You are banned in this room',
    'JR-003': 'Room is not found',
    'JR-004': 'The room is full right now. Please try again in sometime',
    'JR-005': 'You cannot join the room',
    'JR-006': 'Please enter valid code to enter the room',
    'JR-007': 'This event is not active',
    'MEET-001': 'Meeting creation failed.',
    'MEET-002': 'Target creation failed.',
    'MEET-003': 'Meeting already exist.',
    'MEET-004': 'Meeting slot occupied.',
    'MEET-005': `You don't have permission to send meeting request to this user.`,
    'DATE-001': 'Meeting in past not allowed.',
    'RAT-001': 'Please provide a valid type',
    'RAT-002': 'Speaker not found',
    'RAT-003': 'Exhibitor not found',
    'RAT-004': 'Agenda not found',
    'LPL-001': 'User does not exist in database.',
    'LPL-002': 'Agenda do not exists',
    'LPL-003': 'You have not permission to access this',
    'LPL-004': 'Error occured while loading live poll list',
    'PAV-001': 'parameters are missing',
    'PAV-002': 'Poll do not exists',
    'PAV-003': 'The poll has ended',
    'PAV-004': 'The poll is not live yet',
    'PAV-005': 'Poll option not found.',
    'PAV-006': 'You have already voted this option before',
    'PAV-007': 'something went wrong',
    'PAV-008': 'Error occured while loading agenda vote',
    'PC-001': 'Please Provide options',
    'PC-002': 'user does not exist in database.',
    'PC-003': 'Agenda do not exists',
    'PC-004': 'You have not permission to access this',
    'PC-005': 'something went wrong',
    'PC-006': 'Error occured while create agenda poll',
    'MEET-006': `Meeting cancellation failed.`,
    'MEET-007': `Meeting not found.`,
    'MEET-008': `Meeting already cancelled.`,
    'MEET-009': `Can't cancel, Meeting isn't approved yet.`,
    'MEET-010': `Meeting not Pending.`,
    'MEET-011': `Meeting Target slot occupied.`,
    'MEET-012': `Meeting Confirm limit exceeded for user.`,
    'MEET-013': `Meeting Confirm limit exceeded for another user.`,
    'MEET-014': `Venue already booked.`,
    'MEET-017': `Meeting not accepted, Process failed due to error.`,
    'MEET-020': 'Meeting was accepted.',
    'MEET-021': 'Meeting was declined.',
    'MEET-022': 'Meeting was cancelled',
    'AM-001': `Can't accept past meeting.`,
    'AM-002': `Can't reject past meeting.`,
    'RLU-001': 'This event is not active',
    'RLU-002': 'Room is not found',
    'RLU-003': 'channel not exists',
    'RMLC-001': 'Room LiveChat is not found!',
    'RMLC-002': 'Room LiveChat is already deleted!',
    'RMLC-003': 'Room LiveChat is not deleted!',
    'USM-001': 'User slot meeting list Error',
    'EXP-001': 'Exhibitor details update failed',
    'EXP-002': 'Exhibitor analytics failed to load',
    'EXP-003': 'Attendee lead status update failed',
    'EXP-004': 'Attendee engagement list failed to load',
    'ST-001': 'Error occured in fetching settings',
    'ST-002': 'Error occured in updating settings',
    'ST-003': 'Error occured in my privacy settings',
    'ST-004': 'Error occured in updating my privacy settings',
    'ST-005': 'Error occured in updating reset password',
    'ST-006': 'Error occured in delete my data',
    'ST-008': 'The current password you entered is incorrect',
    'CHT-001': 'Error occured while fetching list of users for chat.',
    'RL-001': 'User not exists in this channel',
    'CTS-001': 'Error while contests list fetching',
    'CTS-002': 'Contest not found',
    'CTS-003': 'Feed not found',
    'CTS-004': 'Error while contest details api',
    'CTS-005': 'Error while submitting the quiz',
    'CTS-006': 'Error while creating the comment on feed',
    'CTS-007': 'This Post is not Active',
    'CTS-008': 'The contest is not active',
    'CTS-009':
      'This contest has already ended. Please check the ongoing section to find active contests',
    'CTS-010': 'You can not comment on this entry',
    'CTS-011': 'You have already submitted the entry',
    'CTS-012': 'Comment can not be empty',
    'CTS-013': 'Error while like/dislike feed comment',
    'CTS-014':
      'Sorry, Some parameter are missing. Please enter all required values.',
    'CTS-015': "Comment doesn't exist",
    'CTS-016': 'Feed Not found',
    'CTS-017': 'This Post is not Active',
    'CTS-018': `You don't have permission to do this`,
    'CTS-019': `Error contest feed comment delete`,
    'CTS-020': `Error contest feed comment likes list`,
    'CTS-021': `Error while fetching contest quiz list`,
    'CTS-022': `Error while fetching contest entry list`,
    'CTS-023': 'Contests type should be of type Response',
    'CTS-024': 'Error while fetching contest quiz winner list',
    'CTS-025': 'Error while Entry Feed action',
    'CTS-026':
      'This contest has already ended. Please check the ongoing section to find active contests',
    'CTS-027': 'Error while deleting feed',
    'CTS-028': 'This Post is not Active.',
    'CTS-029': `You don't have permission to do this.`,
    'CTS-030': `Error while fetching the response/entry list`,
    'SAVR-001': 'Your Audio/Video already shared',
    'SAVR-002': 'Kindly remove a meeting participant to add',
    'AAVR-001': 'You not have permission to do this',
    'AAVR-002': 'User has not requested for Audio/Video',
    'SUR-001': 'Survey not found!',
    'SUR-004': 'Survey is not visible',
    'SUR-002': 'Survey already filled!',
    'SUR-003': 'Survey question does not exists!',
    'UCB-001': 'Error occured while user updating busy schedule on calender',
    'UCR-001': 'Error occured while user removeing busy schedule from calender',
    'SRHR-001': 'Your raise hand already sended',
    'ARHR-001': 'You not have permission to do this',
    'ARHR-002': 'User has not requested for raise hand',
    'EFL-001': 'Error occured while fetching feed list.',
    'EFT-001': 'Error occured while fetching custom tag list.',
    'TKT-001': 'Error occured while fetching ticket',
    'TKT-002': 'Invoice data not found.',
    'OAVBM-001': 'User has not requested for Audio/Video,',
    'CU-002': 'Error occured while updating user',
    'BM-006': 'Wrong moduleType while adding/Removing bookmark',
    'MSR-001': 'Speaker mongo ID is invalid ',
    'CQA-001': 'Room not found!',
    'CQA-008': 'QNA not allowed in Room!',
    'CQA-009': 'Polls not allowed in Room!',
    'CQA-010': 'LiveChat not allowed in Room!',
    'CQA-002': 'No moderator found for this room!',
    'CQA-003': 'You can not perform this action!',
    'CQA-004': 'Virtual booth not found!',
    'CQA-005': 'No team member found for the booth!',
    'CQA-006': 'Already upvoted this question!',
    'CQA-007': 'Upvoted already removed from this question!',
    'UCB-002': 'User already have busy schedule on calender',
    'MBM-001': 'User is already mute',
    'BU-001': 'User is already banned',
    'SSJ-001': 'Someone screen already share.So you cannot do the screen share',
    'LPD-001': 'Error in loading link preview data',
    'AC-001': 'Error - Invalid access token!',
    'CPO-001': 'Poll does not exists!',
    'CPO-002': 'Poll is not live!',
    'CPO-003': 'Option is not available!',
    'CPO-004': 'Already given answer for this option!',
    'CPO-005': 'Poll is already live!',
    'CPO-006': 'Poll already ended!',
    'CPO-007': 'Poll is already created!',
    'CPO-008': 'Poll is already visible!',
    'CPO-009': 'Poll is already hidden!',
    'SSL-001': 'Your Screen is not shared',
    'OAV-001': 'User has not requested for Audio/Video',
    'OAV-002': 'Error occured while upadte Audio/Video request',
    'ER-001': 'You cannot end the room',
    'ER-002': 'Error occured while end room',
    'NCE-001': 'Target id is not correct',
    'USR-032': 'Error in set password',
    'USR-033': 'Confirm password and password are not same',
    'CHT-002': 'Error while delete chat data',
    'CHT-003': 'Error while delete chat with user',
    'CHT-004': 'Error while setting message reaction',
    'TZ-001': 'Error while fetching timezone list',
    'LM-001': 'Error while fetching language list',
    'CU-003': 'Nothing to update',
    'MEET-018': 'Error occured while join meeting.',
    'MEET-019': 'Error occured while leave meeting',
    'USR-034':
      'Sorry, Some parameter are missing. Please enter all required values.',
    'USR-035': 'Error while validating the token invitation.',
    'USR-036': 'Invalid token',
    'USR-037': 'Please Login again',
    'USR-038': 'You are logged in from multiple device. Please login again',
    'USR-039': 'Some issue occured while sending the otp. Please try again!',
    'UNSUB-001': 'Invalid type',
    'UNSUB-002': 'Invalid url',
    'QFU-002': 'Error occured while getting votes.',
    'CHT-005': 'Error occured while sending message.',
    'CHT-006': 'Error occured while fetching user list.',
    'UTIL-001': 'Error while Push to kafka',
    'RM-002': 'Room list not found!',
    'RI-001': 'Room Info not found',
    'SPH-002': 'Error occured while getting speaker and host userIds.',
    'NOTIF-001': 'Error occured while updating the notification read.',
    'SLS-002': 'Error occured while updating session live history',

    /**
     * Survey
     */
    SURVEY_NOT_FOUND: 'Survey not found.',
    SURVEY_RESPONSE_NOT_FOUND: 'Response not found.',
    SURVEY_NOT_STARTED_YET: 'The survey will begin shortly.',
    SURVEY_ENDED: 'Sorry, this survey has ended.',
    SURVEY_QUOTA_EXCEEDS:
      'We have already received the required number of responses for this survey. Sorry!',
    SURVEY_STARTED: 'The survey has started.',
    SURVEY_RESPONSE_NOT_EXISTS: "This response doesn't exist.",
    SURVEY_QUESTION_NOT_EXISTS: "This survey question doesn't exist.",
    SURVEY_ADDED: 'Survey added.',
    SURVEY_UPDATED: 'The survey details have been updated.',
    SURVEY_ALREADY_DEACTIVATED: 'This survey is already deactivated.',
    SURVEY_ALREADY_DELETED: 'This survey has been deleted.',
    SURVEY_DELETED: 'Survey deleted.',
    QUESTION_ALREADY_DELETED: 'This question has been deleted.',
    QUESTION_DELETED: 'Question deleted.',
    QUESTION_ADDED: 'A new question has been added.',
    ALREADY_ANSWERED: 'You have already answered this survey once.',
    SURVEY_COMPLETED: 'Survey has already been completed.',

    /**
     * Engage
     */
    CONTEST_RESPONSE_RECORDED:
      'Response successfully recorded. Contest results will be out soon.',
    CONTEST_NOT_FOUND: 'Contest not found.',
    CONTEST_NOT_ACTIVE: 'Contest not active.',
    CONTEST_ENDED:
      'Contest ended. Check the ongoing section for active contests.',
    CONTEST_ALREADY_SUBMIT: 'Contest entry already submitted.',
    CONTEST_UPLOAD_IMAGE: 'Upload Image',
    CONTEST_UPLOAD_VIDEO: 'Upload Video',
    WAIT_MODERATOR_APPROVE: "Kindly wait for the organiser's approval.",
    COMMENT_NOT_ALLOW: 'Comment on entry not allowed.',

    /**
     * Booths
     */
    EXHIBITOR_NOT_FOUND: 'Exhibitor not found.',
    SPONSOR_NOT_FOUND: 'Sponsor not found.',
    INVALID_FILE: 'Invalid File',
    IMAGE_UPLOAD: 'Please upload image',
    RATING_SAVED: 'Rating Saved',
    INVALID_FORMAT: 'Upload valid file format',
    LARGE_IMAGE_SIZE:
      'Re-upload images within the allowed dimensions. Images greater than 1024 x 1024 pixels are not allowed.',
    SPOTLIGHT_IMAGE_SIZE_ERR:
      'Upload another image as minimum width and height should be 1036x320px.',
    LIST_BANNER_IMAGE_SIZE_ERROR:
      'Upload another image as minimum width and height should be 840x220px.',
    INVALID_FORMAT_FOR_SURVEY:
      'Upload valid format of the file (image, pdf, doc, ppt and excel).',

    /**
     * People
     */
    ATTENDEE_NOT_FOUND: 'Attendee not found.',
    SPEAKER_NOT_FOUND: 'Speaker not found.',
    BUSINESS_CARD_TARGET_NOT_IN_COMMUNITY:
      "You can't request a user who is not a part of this Community.",
    BUSINESS_CARD_REQUEST: 'Business card request sent!',
    BUSINESS_CARD_ALREADY_REQUESTED: 'You have already requested.',
    BUSINESS_CARD_ERROR: "You can't perform this operation.",
    USER_HAS_BLOCKED_YOU:
      "You can't send a message to a user who has blocked you.",
    CANT_BLOCK_USER_CHAT:
      "You can't block a user who is not in this Community.",
    CHAT_USER_BLOCKED_SUCCESS: 'User blocked successfully.',
    CHAT_USER_UNBLOCKED_SUCCESS: 'User unblocked successfully.',
    COMMUNITY_NOT_ACTIVE: 'User not active in the Community.',
    USER_NOT_FOUND: 'User not found.',

    /**
     * Login/Signup
     */
    INVALID_ACCESS_TOKEN: 'Please login again.',
    FB_REGISTER_FAIL: 'Facebook login issue. Try again.',
    EVENT_NOT_FOUND: 'Event not found.',
    EVENT_NOT_ACTIVE: 'Event not active.',
    INVALID_CREDENTIAL: 'Enter valid credentials.',
    EMAIL_MISSING: 'E-mail ID missing.',
    INVALID_EMAIL: 'Enter a valid e-mail.',
    ACCOUNT_INACTIVE: 'Account inactive.',
    ACCOUNT_BLOCKED: 'Entry not permitted by the organiser.',
    ACCOUNT_DELETED: 'Account deleted.',
    EMAIL_NOT_REGISTERED: 'Unregistered e-mail ID. Enter registered e-mail ID.',
    LOGIN_SETTINGS_CHANGED: 'Login settings changed. Restart the app again.',
    INCORRECT_PASSWORD: 'Current password is wrong. Please try again.',
    LOGIN_ID_NOT_EXIST: "Login ID doesn't exist.",
    LOGIN_ID_NOT_EXIST_CONTACT_SUPPORT:
      "Login ID doesn't exist. Contact %%SUPPORT_EMAIL%% for more information.",
    INVALID_OTP: 'Enter a valid Login Code to continue.',
    CONFIRM_PASSWORD_MISMATCH: 'Confirm password mismatch.',
    INVALID_PHONE_NUMBER: 'Enter a valid phone number.',
    RSVP_ID_MISSING: 'RSVP ID missing.',
    WAITLIST_ID_MISSING: 'Waitlist ID missing.',
    TRANSACTION_INDIVIDUAL_ID_MISSING: 'Transaction individual ID missing.',
    INVALID_LOGIN_TYPE: 'Invalid Login type.',
    USER_NOT_IN_EVENT: 'User not present in any event.',
    USER_IN_MULTIPLE_EVENT:
      'User in multiple events. Please contact organizer.',
    INVALID_TOKEN: 'Invalid token',
    OTP_VERIFIED: 'Login Code verified',
    EMAIL_ALREADY_REGISTERED:
      'Email ID already registered. Use current ID or login in with another ID.',
    LOGIN_FAIL_USER_NOT_IN_EVENT:
      'Login failed. Unregistered user for this event.',
    CONTACT_ADMIN_FOR_LOGIN_DETAILS:
      'Contact event admin to provide login credentials.',
    CONTACT_ADMIN_FOR_LOGIN_DETAILS_CONTACT_SUPPORT:
      'Contact event admin at %%SUPPORT_EMAIL%% to provide login credentials.',
    OTP_SENT_TO_PHONE_NUMBER: 'Login Code sent to your phone number.',
    ACCOUNT_ACCESS_LOCK: 'Account locked. Please try after %%min%% min.',
    MEETING_REQUEST_LIMIT_OVER:
      'Sorry, you reached the maximum number of requests.',
    MEETING_CONFIRM_LIMIT_OVER_FOR_USER:
      'Sorry, you have reached the maximum number of meetings.',
    MEETING_CONFIRM_LIMIT_OVER_FOR_ANOTHER_USER:
      'Sorry, the user has reached the maximum number of meetings.',
    PASWORD_LENGTH_ERROR: 'Minimum 8 characters password required.',
    OTP_BEFORE_TIME: 'You can try for a new Login Code after 30 seconds.',
    ACCOUNT_BLOCKED_FOR_SOMETIME:
      'Too many unsuccessful attempts. Try again later.',
    INCORRECT_CREDENTIALS: 'Invalid credentials',
    OTP_EXPIRED: 'Login Code expired. Generate a new one.',
    OTP_ACCOUNT_BLOCKED_FOR_SOMETIME:
      'Multiple Login Code requests. Try again later.',
    PASSWORD_STRENGTH:
      'Password must be minimum 8 characters with digits, lowercase, uppercase and special characters.',
    INCORRECT_PASSWORD_SUPPORT:
      'Enter correct password or contact %%SUPPORT_EMAIL%% for support.',

    /**
     * Home
     */
    POLL_OPTIONS: 'Please provide options.',
    DELETED_FEED: 'This Feed has been deleted.',
    FEED_NOT_ACTIVE: 'Post not Active',
    FEED_ALREADY_LIKED: 'Already Liked',
    FEED_NOT_EXIST: "Post doesn't exist.",
    FEED_REPORTED:
      'Thanks for reporting the post. Necessary action will be taken.',
    FEED_NOT_APPROVED: 'Post not approved.',
    FEED_UPGRADE_TICKET:
      'Upgrade your ticket to post comments in this Community.',
    FEED_COMMENT_MSG: "Comment posted, please wait for organiser's approval.",
    FEED_COMMENT_NOT_FOUND: "Comment doesn't exist.",
    FEED_COMMENT_ALREADY_DELETED: 'Comment already deleted.',
    FEED_COMMENT_DELETE: 'Comment Deleted',
    FEED_COMMENT_REPORTED:
      'Thanks for reporting the comment. Necessary action will be taken.',
    FEED_NOT_FOUND: 'Feed not found.',
    POLL_CREATED: 'Poll Created',
    POST_PINDDED: 'Post Pinned',
    POST_UNPINNDED: 'Post Unpinned',

    /**
     * Chat & Notifications
     */
    NOTIFICATION_LIST_CLEAR: 'Cleared',
    CANT_MSG_USER: "You can't message this user.",
    CHAT_DISABLED: 'User disabled chat feature.',
    CHAT_PERMISSION_ERROR: "You can't message this user.",
    CHAT_NOT_FOUND: 'Chat not found.',
    PROVIDER_NOT_FOUND: 'Media Provider not found.',
    MEDIAID_NOT_FOUND: 'MediaId not found.',
    NO_CHAT_WITH_TARGET: 'No chat with target.',
    CANT_DELETE_CHAT: 'You can only delete your chats.',
    DELETE_SINGLE_CHAT_SUCCESS: 'Chat deleted successfully.',
    DELETE_MULTI_CHAT_SUCCESS: 'Chats deleted successfully.',
    NOTIFICATION_MEETING_SENT: 'has sent you a meeting request.',
    NOTIFICATION_MEETING_ACCEPT: 'has accepted your meeting request.',
    NOTIFICATION_MEETING_ACCEPT_WITH_VENUE:
      'has accepted your meeting request. The venue for the meeting is:',
    NOTIFICATION_MEETING_VENUE: 'The venue for the meeting is:',
    NOTIFICATION_MEETING_REJECT: 'has declined your meeting request.',
    NOTIFICATION_FEED_TAG: 'mentioned you in a post.',
    NOTIFICATION_FEED_LIKE: 'liked your post.',
    NOTIFICATION_FEED_INTEREST: 'has shown interest in your post.',
    NOTIFICATION_FEED_COMMENT: 'commented on your post.',
    NOTIFICATION_BUSINESS_CARD_SENT: 'has sent you a Business Card request.',
    NOTIFICATION_BUSINESS_CARD_ACCEPT:
      'has accepted your Business Card request.',
    NOTIFICATION_BUSINESS_CARD_REJECT:
      'has rejected your Business Card request.',
    NOTIFICATION_PROFILE_VIEW: 'viewed your profile',

    /**
     * Rooms
     */
    ROOM_IS_NOT_LIVE: 'Room not live yet. Try again later.',
    ROOM_NOT_FOUND: 'Room not found.',
    ROOM_FULL: 'Room is full. Try again in sometime.',
    CAN_NOT_JOIN_ROOM: 'You cannot join the room.',
    INCORRECT_ROOM_CODE: 'Enter a valid code to enter the Room.',
    ROOM_NOT_STARTED_YET: 'Room not started yet.',
    AGENDA_COMMENT_NOT_EXISTS: "Question doesn't exist.",
    INVALID_TIMEZONE: 'Invalid Timezone',
    LOUNGE_LEFT_MEETING: 'You have left the meeting.',
    LOUNGE_MEETING_TIME_END: 'The Meeting has ended.',
    FEEDBACK: 'Thanks for your feedback.',
    ROOM_USER_BAN: 'You are banned in this Room.',
    ROOM_AV_ALREADY_SHARED: 'Audio/Video already shared.',
    ROOM_AV_ALREADY_REQUESTED: 'Audio/Video already requested.',
    REQUESTED_SUCEESSFULLY: 'Request Sent Successfully.',
    USER_ALREADY_SHARED_AV: 'User Audio/Video already shared.',
    USER_NOT_REQUESTED_SHARED_AV: 'User has not requested for Audio/Video.',
    ALREADY_RAISE_HAND_IN_CALL:
      'Remove an attendee in the call who has already raised hand and then add this attendee.',
    RECORDING_REQUEST_ALREADY: 'Recording request already recieved,',
    RECORDING_NOT_ALLOW: 'Recording is not allowed in this Room.',
    CAN_NOT_END_ROOM: 'You cannot end the Room.',
    USER_NOT_EXITS_CHANNEL: "User doesn't exits in this channel",
    CHANNEL_NOT_EXITS: "channel doesn't exists",
    PERMISSION_ERROR: "You don't have permission to do this",

    /**
     * Longe
     */
    ACTIVATE_LOUNGE_TABLE_FIRST: 'Turn on Lounge table first.',
    TABLE_ADDED: 'Lounge table added.',
    LOUNGE_TABLE_NOT_EXISTS: 'Lounge table does not exit.',
    LOUNGE_TABLE_DELETED: 'Lounge table sucessfully deleted',
    ACTIVATE_LOUNGE_FIRST: 'Turn on Lounge networking first.',
    LOUNGE_SETTING_UPDATED: 'Lounge setting updated',
    LOUNGE_NOT_AVAILABLE: 'Lounge is not available in this event.',
    TABLE_LIST_LIMIT_DONE:
      'Table limit exceeded. Contact Administrator to add more tables.',
    ADMIN_ACTIVATE_LOUNGE_FIRST:
      'Contact Administrator to activate the Networking Lounge.',
    LOUNGE_IS_OFF: 'Lounge networking is off currently.',
    SLOT_IS_CLOSED: 'Sorry, this slot is closed for video call.',
    SEAT_NUMBER_NOT_EXITS: 'This seat number does not exist.',
    ALREDAY_JOINED: 'Leave the current table to join a new table.',
    TABLE_BUSY: 'Sorry, this table is currently busy.',
    SOMEONE_ELSE_TOOK_SEAT: 'Sorry, this seat is taken.',
    EXHIBITOR_LOUNGE_IS_OFF: 'Currently Exhibitor Lounge networking is off.',
    EXHIBITOR_UNAVAILABLE:
      'Currently the exhibitor is unavailable for a meeting.',
    UNKNOWN_EXHIBITOR: 'Unknown exhibitor for this seat.',
    EXHIBITOR_ALREADY_JOINED: 'One of your exhibitors is already there.',
    CHANNEL_TIME_LESS_TO_UPDATE:
      'Updating meeting count 2 minutes before not allowed',
    ACTIVATE_EXHIBITOR_LOUNGE_FIRST: 'Please turn on Exhibitor Lounge first.',
    ADMIN_EXHIBITOR_ACTIVATE_LOUNGE_FIRST:
      'Contact administrator to activate the Exhibitor Networking Lounge.',
    ACTIVATE_ATTENDEE_LOUNGE_FIRST: 'Turn on Attendee Lounge first.',
    INVALID_TABLE_CAPACITY: 'Invalid table capacity.',
    SPONSOR_LOUNGE_IS_OFF: 'Sponsor Lounge networking is currently off.',
    SPONSOR_UNAVAILABLE: 'The sponsor is currently unavailable for a meeting.',
    UNKNOWN_SPONSOR: 'Unknown sponsor for this seat.',
    ACTIVATE_SPONSOR_LOUNGE_FIRST: 'Turn on Sponsor Lounge first.',
    ADMIN_SPONSOR_ACTIVATE_LOUNGE_FIRST:
      'Contactadministrator to activate the Sponsor Networking Lounge.',

    /**
     * Profile, setting, scheduele
     */
    ADD_FILE_BRIEFCASE: 'This file has been added to your Briefcase.',
    HIDE_FILE_BRIEFCASE: 'This file is hidden.',
    UNHIDDEN_FILE_BRIEFCASE: 'This file has been unhidden.',
    REMOVE_FILE_BRIEFCASE: 'This file has been removed from the Briefcase.',
    FILE_ALREADY_IN_BRIEFCASE: 'This file already exists in your Briefcase.',
    FILE_NOT_FOUND: 'File not found.',

    /**
     * Sessions
     */
    AGENDA_NOT_FOUND: 'Agenda Not Found.',
    REMINDER_ADDED: 'Reminder Added',
    REMINDER_REMOVED: 'Reminder Removed',
    REGISTRATION_NOT_STARTED: 'Registrations Not Started Yet!',
    REGISTRATION_CLOSED: 'Registrations Closed!',
    REGISTRATION_LIMIT_EXCEED: 'Registration limit exceeded.',
    ALREADY_REGISTER_IN_SESSION: 'Already Registered',
    NOT_REGISTER_IN_SESSION: "You're Un-registered",
    SESSION_REGISTRATION_DONE: 'Registration Successful!',
    SESSION_REGISTRATION_PENDING:
      'Registration waitlisted. Status update will be sent via mail.',
    SESSION_UNREGISTERD: 'Deregisterd Successfully!',
    AGENDA_COMMENT_MSG: "Question Posted. Waiting organiser's approval.",
    POLL_DEACTIVATED: 'Poll deactivated by the user.',
    BLOCK_PERMISSION_ERROR: 'Blocking this user is not permitted.',
    ALREADY_BLOCKED: 'User is already blocked.',
    ALREADY_UNBLOCKED: 'User is already unblocked.',
    BLOCKED_IN_LIVE_CHAT: 'You are blocked for this live chat.',
    AGENDA_COMMENT_DELETE: 'Question removed successfully.',
    POLL_NOT_FOUND: "Poll doesn't exist.",
    SESSION_ENDED: "Sorry! You can't chat on ended session.",
    SAVED: 'Saved Successfully',
    REJECTED: 'Rejected Successfully',
    APPROVED: 'Approved Successfully',
    AGENDA_LIVE_POLL_CREATED: 'Poll Created',
    AGENDA_POLL_LIVE: 'Poll is Live',
    AGENDA_LIVE_POLL_END: 'Poll Ended',
    AGENDA_LIVE_POLL_SHOW: 'Poll result visible to attendees.',
    AGENDA_LIVE_POLL_HIDE: 'Poll result hidden from attendees.',
    AGENDA_LIVE_POLL_DUPLICATE: 'Poll Duplicated',
    AGENDA_LIVE_POLL_DELETED: 'Poll Deleted',
    AGENDA_LIVE_POLL_EDIT: 'Poll Edited',
    UPVOTE_ADDED: 'Upvoted Successfully',
    UPVOTE_REMOVED: 'Upvote Removed',
    CHAT_PINNED: 'Chat Pinned',
    CHAT_UNPINNED: 'Chat Unpinned',
    NOT_PERMISSION_ATTENDE_SESSION: 'Not permitted to attend the session.',
    SESSION_NOT_STARTED: 'Session yet to start. Please try again later.',
    LIVE_CHAT: 'Chat',
    QUESTION_AND_ANSWERS: 'Q&A',
    LIVE_POLLS: 'Polls',
    ATTENDEE_LIST: 'Attendees',
    SESSIONS: 'Sessions',

    /**
     * Meeting
     */
    MEETING_IN_PAST: "You can't set meeting in the past",
    SELF_MEETING: "You can't set meeting with you",
    ALREADY_MEETING_REQUESTED:
      'You have already sent a meeting request at this slot',
    OCCUPIED_SLOT: 'Your slot is occupied',
    TARGET_OCCUPIED_SLOT: 'Target slot is occupied',
    ALREADY_VENUE_BOOKED: 'Venue is already booked for this slot',
    MEETING_NOT_PENDING: 'Meeting is no longer in pending state',
    CANT_ACCEPT_PAST_MEETING: "You can't accept past meeting",
    CANT_REJECT_PAST_MEETING: "You can't reject past meeting",
    MEETING_ACCEPTED: 'Meeting accepted',
    MEETING_DECLINED: 'Meeting declined',
    MEETING_DISABLED: 'User has disabled meeting requests.',
    MEETING_PERMISSION_ERROR: "You can't send meeting request to this user",
    MEETING_CLOSE_SLOT_IN_PAST: "You can't close meeting slots in the past",
    MEETING_CLOSE_SLOT_REMOVED: 'Removed',
    NOT_IN_COMMUNITY: 'User not found in community',
    MEETING_LIMIT_OVER:
      'Your meeting quota is over, Please contact administrator to increase meeting quota',
    ALREADY_CANCEL: 'Meeting already canceled',
    MEETING_NOT_APPROVE_CANCEL: "Can't cancel, Meeting isn't approved yet.",
    CANCELED: 'Successfully canceled',
    SLOT_IS_CLOSED_MEETING: 'Sorry, this slot is closed for meeting',

    /**
     * unsubscribeUsers
     */
    UNSUBSCRIBE_SUCCESS: 'Successfully unsubscribed',
    INVALID_TYPE: 'Invalid Type',
    INVALID_URL: 'Invalid Url'
  }
};

// NOTE:: Please add your keys in "dev/locales/i18n/en.json" files. This file will be deleted soon.
